# Generated by Django 4.2.7 on 2026-03-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_prediction', models.CharField(help_text="The model's predicted type of trash", max_length=255)),
                ('user_prediction', models.CharField(help_text="The user's predicted type of trash", max_length=255)),
                ('image_data', models.TextField(help_text='Base64-encoded image data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
